### ISSUE TITLE
Support for foreign CSS classes

### ISSUE THREAD

**Issue by mikolajpp** [mdgriffith/stylish-elephants#22]
Some complex JS apps for which there won't be an equivalent 
in Elm in the near future, like web editors require custom CSS styling. 

I have looked through elephants source code, and it does look like supporting 
this feature would require custom rendered as classes name and properties are closely linked. 

Implementing this would probably require maintaining two renderers with the only difference 
being the class name. 

On the other hand, having something like 
`foreign className [style1, style2, style3, style4, ...]`
work would be very useful. 

Examples: Ace/Codemirror editors, Facebook draft.js and other apps 
for which it will take many years to be ported to pure Elm. Allowing styling to be specified with 
style-elements would allow us to close these JS apps totally behind ports. 

If this is desirable, I am up for implementing this myself.

**Comment by mdgriffith** [comment]
So, this sounds like something to write using `elm-css`'s engine instead of trying to include directly in the style-elements repo.  But even then I'd be a little hesitant.

Not all style-element concepts can translate directly into css you could use in other places.  The first being the idea of an `el` which can only have one child, there'd be no way to enforce that.  Also, alignment currently needs some inserted DOM nodes in some cases to work correctly, so it can't be implemented via css-only.

So, then we'd have to say "Oh, when using this part of the library, generate these style classes, but also keep all this other stuff in mind when using them because things will break otherwise", which gets away from the unbreakable style aspiration that started this whole project. :)

**Comment by mikolajpp** [comment]
Over the weekend, I actually abandoned this idea myself.

Now the only thing I really need is css-elm using standard color library, but this is a thing for them : )
