### ISSUE TITLE
bring back wrappedRow?

### ISSUE THREAD

**Issue by mdgriffith** [mdgriffith/stylish-elephants#5]
It seems to show up mostly with wrapping tokens, and `paragraph` might not be sufficient for this.

Also, because we're using inline positioning for paragraph, spacing might be funky.

**Comment by mdgriffith** [comment]
Spacing is currently very hard to implement for wrappedRow, in both directions.

Currently spacing in a row is implemented as `margin-left` on all elements except the first one.

Since we don't know when a row will wrap, we can't remove the margin on the first element that wraps around.

Also, the vertical spacing between elements could nominally be specified by setting `margin-top` on all elements not in the first row, but again we don't know when the elements begin to wrap.

in v4 spacing was specified by setting margin on every child element and setting a negative margin on the parent.  This led to some funky behavior in some browsers though and also required nesting elements.

**Comment by mdgriffith** [comment]
So, the approach I took to solving this was just to make `spacing` work on a `paragraph`.

There is one minor catch, that the padding on the paragraph will be at least 1/2 the spacing value set.  That doesn't seem to be a big deal though unless I'm missing something.

**Comment by kuon** [comment]
Just hit another issue, how can I make a container that has `clip` set, this container containers item that should be vertically centered if there is only 1 row, but when wrapping they should spread in the vertical space.

Example: https://codepen.io/anon/pen/EozoGx

**Comment by mlms13** [comment]
Just to chime in after a quick chat on slack... I wanted to mention that I seem to make the same grid-of-cards layout over and over again. Enough so that it would be really fantastic if style-elements could help ease my pain with this one.

Example mockup: https://dribbble.com/shots/3141791-Agile-CRM-Contacts/attachments/665699

I think one common approach to this problem is to use `margin-left` on all of the children, including the first one, then use negative margin on the parent to compensate. But this is the kind of strategy that could have weird, gross edge cases (which makes it the perfect candidate to be solved by style-elements so that I never have to think about it again!)
