### ISSUE TITLE
Font.align* not aligning

### ISSUE THREAD

**Issue by martindlarsson** [mdgriffith/stylish-elephants#51]
I cannot get text to align to left or right.

This code should align the text left, right?
`
    Element.layout [] <|
        Element.column
            [ width (px 200)
            , height (px 80)
            , Font.alignLeft
            , Border.color Color.red
            , Border.width 1
            , Border.solid ]
            [ Element.text "Hello!!"]
`

https://ellie-app.com/8KpTcnB7Ra1/0

**Comment by atlewee** [comment]
You are aligning the column itself, not the text element.
In v5 (stylish-elephants) you have to align the children.
So to align your text you need to wrap your text in an element.

```
Element.layout [] <| 
    Element.column 
        [ width (px 200) 
        , height (px 80) 
        , Border.color Color.red 
        , Border.width 1 
        , Border.solid 
        ] 
        [ Element.el [ Font.alignLeft ] (Element.text "Hello, I'm left aligned!!") 
        , Element.el [ Font.alignRight ] (Element.text "Hello, I'm right aligned!!") 
        ]
```

**Comment by martindlarsson** [comment]
Oh, thanks. I haven't tried it but I believe you.
Since Font.size and others cascade down, one would assume Font.align* would too. Clarification in documentation needed if not so. I can help with that.

**Comment by martindlarsson** [comment]
So I tried your approach and it works. There has to be a combination of en Element.el with alignLeft. I was using Font.alignLeft instead of Element.alignLeft and without the Element.el. I tried Element.alignLeft without the Element.el and it did not align the text left.

So I am a bit confused about the difference between Element.align and Font.align. And the other question is if the Element.alignLeft should cascade down.

**Comment by mdgriffith** [comment]
I definitely understand the confusion.  `Font.alignLeft` is much more apparent and distinctive in the context of writing paragraphs as opposed to just trying to place a sentence on one side or another.  Maybe this is an argument that Font alignment should be removed and be constructed like `paragraphLeft [] []` instead of an attribute. 🤔  Definitely something I will be thinking about.

For the new version of the library, the default for most elements is to align children to the left and top, so that might help out with what you're trying to do.
