### ISSUE TITLE
A `behind` node covers parent element

### ISSUE THREAD

**Issue by akavel** [mdgriffith/stylish-elephants#90]
I tried to reproduce a reduced example on Ellie: https://ellie-app.com/pFYfDBmdnxa1

In my Firefox (60.0.1), it renders as in the screenshot, with gray area covering the menu:

<img src="https://user-images.githubusercontent.com/273837/40880247-6df23c6a-66ad-11e8-9d7e-160e9876b7e3.png" width="50%" height="50%"/>

although from the code, I'd expect the gray area should be `behind` the menu, and the menu should show as non-grayed-out:

```elm
viewMenu =
    column
        [
         height fill
        , Background.color Color.white
        , Font.color Color.black
        -- try to do "grayed out" effect behind the menu
        , behind
            <| el
                [ width (px 100000)
                , height (px 100000)
                , moveUp 50000
                , moveLeft 50000
                , Background.color Color.gray
                , alpha 0.75
                ]
                none
        ]
        [ text "Menu item 1"
        , text "Menu item 2"
        ]
```

**Comment by mdgriffith** [comment]
Ok, so I looked into this and there are a few things that pop up.

The way I got it to work is that the `behind` element will be behind the content of an element, but in front of it's background.

so, the layering would be
`columnBackground -> behind element -> column content`

Because it's not actually behind `columnBackground`, I'm thinking of renaming `behind` to `behindContent`.

One of the reasons for this is that having the behind element go completely behind the column seems to be sorta impossible in a way that won't mysteriously break later on(you have to set z-index:0 on the parent of the column, and require that z-index is not set on the column itself).

I realize this doesn't cover the usecase you were thinking of where you can click outside of a menu to close it, however I was thinking that you might want to look into global event handlers instead. 

So, you could have an event handler on the menu which prevents bubbling up to the root node.
And then you could be listening globally for clicks when a menu is open.

**Comment by akavel** [comment]
@mdgriffith Thanks for the suggestion; is it possible to do the events stuff you're talking about using stylish-elephants? Or does this require some out-of-framework approach, I assume via `Html`? I'm not versed in JS, don't have good understanding of the bubbling prevention and global listening ideas for now...

**Comment by mdgriffith** [comment]
Correct, it's outside of `stylish-elephants`.  

Specifically, you first want to listen for mouse clicks using the [Mouse package](http://package.elm-lang.org/packages/elm-lang/mouse/1.0.1/Mouse).

Then, you'll want to create an event handler for the menu that stops propagation (which is where an event bubbles up to the top and is eventually caught by a global handler like `Mouse.clicks`)

To do that you'd first create a new event handler.

```elm
import Html.Events
import Json.Decode as Json

onClickNoBubble msg =
    Element.htmlAttribute
        (Html.Events.onWithOptions "click"
            { stopPropagation = True, preventDefault = False }
            (Json.succeed msg)
        )

```

Then you can use `onClickNoBubble` instead of `onClick`.
